### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: shawn-phy
# description: This will be meta HTML tag content. This can be ignored.
description: Personal website built with jekyll
# baseurl: The subpath of your site
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: shawn-phy
# typing_text: This will be typed before 'scroll down for more'.
typing_text: Student Engineer 
# email: Your E-Mail address for the email button.
email: philipoyuga14@gmail.com
# For every social button you want to display, set your username or userid
github_username: shawn-phy
codepen_username: shawn-phy
dev_username: shawn_phy
linkedin_username: shawn-philip-31361a210
twitter_username: OyugaPhilip

# ABOUT ME SECTION
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: About Me
# about_me_description: This will be displayed under the title.
about_me_description: My name is Philip Shawn an undergraduate student at JKUAT studying Electronic And Computer Engineering.
                      I am always enthusiastic about learning and implementing new technologies such as Artficial Intelligence and Cloud computing.
                      I am also a huge fan of federated social media instances as shown in some of the open source projects I have done.
                      In my free time I love playing CTF challenges specifically the digital forensics but I'm still learning.

# SKILLS SECTION
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where I've hosted my cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: https://www.dropbox.com/s/tr6twmvxa92hig4/resume.pdf?dl=0

# PROJECTS SECTION
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Projects
# show_os_projects:
show_os_projects: true
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
contact_description: Reach out via any of the following and Lets connect to build beautiful things ❤️!

# GITHUB-METADATA
repository: shawn-phy/shawn-phy.github.io
projects:
  sort_by: pushed
  exclude:
    archived: false
    forks: false
    projects:

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: "UA-158757509-2"

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
